# Copyright (c) K-Society and contributors. All rights reserved. Licensed under the Microsoft Reciprocal License. See LICENSE.TXT file in the project root for full license information.
#

branches:
  only:
    - master
    - develop

image: Visual Studio 2022

version: 1.0.0.{build}
platform: Any CPU
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_XMLDOC_MODE: skip
  
#before_build:
#  - ps: dotnet --info

build:
  verbosity: minimal

build_script:
  - appveyor.cmd

test: off

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

skip_branch_with_pr: true
skip_tags: true

#build:
#  publish_nuget: true

artifacts:
  - path: build\**\Release\*.nupkg
    name: NuGetPackage
 #- path: build\**\Release\*.snupkg
 #  name: NuGetPackage
#- path: build\Release\**\*.msi
#  name: msi

deploy:
  - provider: NuGet
    server: https://ci.appveyor.com/nuget/k-society/api/v2/package
    api_key:
      secure: jIQOXURv/wJ2bys5OTJpp+zTyN8tyVAnczeodJUK3Nw=
    skip_symbols: true
    symbol_server:
    artifact: /.*\.nupkg/
    on:
      branch: /^(master|develop)$/
      
  - provider: NuGet
    server: 
    api_key:
      secure: bOgKbntjK/dMmw71pGK590FEZxLbgGSMMRdcesvYD0YBd0D8YoTNhCFHUxTUIKyw
    skip_symbols: true
    symbol_server: 
    artifact: /.*\.nupkg/
    on:
      branch: master