//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using KSociety.Base.App.Shared;
using ProtoBuf;


namespace KSociety.Com.App.Dto.Req.Add.Common
{
	
	
	/// <summary>
	/// Test
	/// </summary>
	[ProtoBuf.ProtoContractAttribute()]
	public class Test : IRequest
	{
		
		/// <summary>
		/// Test
		/// </summary>
		public Test()
		{
		}
		
		/// <summary>
		/// Test
		/// </summary>
		public Test(System.Guid id, int automationTypeId, int automationTypeId1)
		{
			this._id = id;
			this._automationTypeId = automationTypeId;
			this._automationTypeId1 = automationTypeId1;
		}
		
		/// <summary>
		/// 
		/// </summary>
		private System.Guid _id;
		
		/// <summary>
		/// 
		/// </summary>
		private int _automationTypeId;
		
		/// <summary>
		/// 
		/// </summary>
		private int _automationTypeId1;
		
		/// <summary>
		/// 
		/// </summary>
		[ProtoBuf.ProtoMemberAttribute(1)]
		[ProtoBuf.CompatibilityLevelAttribute(ProtoBuf.CompatibilityLevel.Level200)]
		public System.Guid Id
		{
			get
			{
				return _id;
			}
			set
			{
				this._id = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[ProtoBuf.ProtoMemberAttribute(2)]
		public int AutomationTypeId
		{
			get
			{
				return _automationTypeId;
			}
			set
			{
				this._automationTypeId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[ProtoBuf.ProtoMemberAttribute(3)]
		public int AutomationTypeId
		{
			get
			{
				return _automationTypeId1;
			}
			set
			{
				this._automationTypeId1 = value;
			}
		}
	}
}
