name: Build KSociety.Base

on:
  push:
    branches:
      - master
      - develop
      - experimental
  pull_request:
    branches:
      - master
      - develop
      - experimental
  workflow_dispatch:
    inputs:
      tags:
        manual: true
        
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_XMLDOC_MODE: skip
  
jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build KSociety.Base
        shell: cmd
        run: ./build.cmd
        